### PR TITLE
added wavelegnth for ENVI binary raster-style files.

### PR DESCRIPTION
**Pull request by bkarpowicz**
Hi,
I found your plugin quite useful, and thought it would be useful to add wavelength for hyperspectral applications. I've tested this on Mac OS with ENVI-style binary raster files, and a hdf 5 file I've been developing for our own data distribution (which mirrors the metadata found in ENVI-style rasters). I'm brand new to qgis development, but I'm hoping you might find it useful.

Cheers,
Bryan

### CODE REVIEW

**Comment by etiennesky** [comment]
this looks nice. Can you provide a dataset (a link would be ok) so I can test this change?

**Comment by bkarpowicz** [comment]
Sure, here is a binary raster/envi header. If it takes forever, I could subset it...

https://dl.dropboxusercontent.com/u/60117872/NIS01_20130611_094717_rdn_ort
https://dl.dropboxusercontent.com/u/60117872/NIS01_20130611_094717_rdn_obs_ort.hdr

**Comment by etiennesky** [comment]
that file is huuuuuge. please subset it to something manageable (a few mb) or provide another file, thanks.

**Comment by bkarpowicz** [comment]
Sure, I subset the image. When you do that in ENVI it puts extra "stuff" in the file. I updated the the latest version to parse out the string correctly. I've also tried it with the original file, and it works. The files are here:
https://dl.dropboxusercontent.com/u/60117872/subset_clean.hdr
https://dl.dropboxusercontent.com/u/60117872/subset.hdr
https://dl.dropboxusercontent.com/u/60117872/subset.img

subset_clean is the header where I cleaned out the band name information to check that it still worked with my latest modification.

**Comment by etiennesky** [comment]
I am getting this error. Probably missing a call to open()

Traceback (most recent call last):
  File "/home/tourigny/.qgis2/python/plugins/valuetool/valuewidget.py", line 402, in printValue
    self.showValues()
  File "/home/tourigny/.qgis2/python/plugins/valuetool/valuewidget.py", line 407, in showValues
    self.plot()
  File "/home/tourigny/.qgis2/python/plugins/valuetool/valuewidget.py", line 487, in plot
    f
NameError: global name 'f' is not defined

**Comment by etiennesky** [comment]
got it to work by removing the 2 lines that refer to f in printValue(). 

Only thing missing is the title when using qwt. Can you add that?

Aside from that looks good! I'll merge once it's fixed by you.

**Comment by bkarpowicz** [comment]
I think I removed the two f in this version. I've added a piece that should mirror the matplotlib behavior in qwt. I don't have a way to test it currently.

**Comment by bkarpowicz** [comment]
I've been able to test functionality with x-axis title using qwt. It works, and mirrors the behavior of mpl.

**Comment by etiennesky** [comment]
hi,

it works but only the title is missing

**Comment by bkarpowicz** [comment]
Are you sure you're using the latest update? The xlabel is there. I don't recall there being a title for the plot itself.

tst

**Comment by etiennesky** [comment]
sorry I didn't see your latest commits, works fine, I will merge but not release right away

**Comment by bkarpowicz** [comment]
cool. Thanks!

**Pull request merged**
